language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t dymek669/docker-react .

script:
  - docker run -e CI=true dymek669/docker-react yarn test